Ravi/Aishwarya | Allow okta-config to be present outside the bundled jar
bostonaholic/ring-okta pull request #4
Opened 2020-09-11 09:45 UTC by ravik-karn-tw

2020-09-12 03:04 UTC, bostonaholic requested changes
Overall I believe these changes make sense. Thank you for the PR. I have one small suggestion before merging.

2020-09-12 03:04 UTC, bostonaholic commented on src/ring/ring_okta/session.clj
> +  (let [okta-response (saml/respond-to-okta-post (slurp (io/reader okta-config-location)) params)]
I believe the docs for `clojure.java.io/reader` suggest:

> Should be used inside with-open to ensure the Reader is properly closed.

https://clojure.github.io/clojure/clojure.java.io-api.html#clojure.java.io/reader

Is it possible for you to wrap the call in `with-open` as the docs suggest?

2020-09-12 03:05 UTC, bostonaholic commented
Also, I made some minor code style changes on master. You may need to rebase your branch to clean up the conflicts. My apologies.

2020-09-12 07:53 UTC, ravik-karn-tw commented on src/ring/ring_okta/session.clj
> +  (let [okta-response (saml/respond-to-okta-post (slurp (io/reader okta-config-location)) params)]
Good suggestion.. 

I have made the required changes

2020-09-13 04:49 UTC, bostonaholic commented on src/ring/ring_okta/session.clj
> +  (let [okta-response (saml/respond-to-okta-post (slurp (io/reader okta-config-location)) params)]
Thanks @ravik-karn-tw. Looks good to me! I'll be merging and releasing `0.5.0` shortly.

2020-09-13 04:50 UTC, bostonaholic approved these changes
Thank you for the feature suggestion and putting in the work to make it happen!

2020-09-13 04:51 UTC, merged

2020-09-13 06:12 UTC, bostonaholic commented
@ravik-karn-tw This has been merged and released as `0.5.0`. Please let me know if you have any issues. Thanks again for you help!

2020-09-14 03:28 UTC, ravik-karn-tw commented
> @ravik-karn-tw This has been merged and released as `0.5.0`. Please let me know if you have any issues. Thanks again for you help!

@bostonaholic Thanks for the help